packages:
  - server
  - admin
  - web
  - packages/*

overrides:
  '@nestjs/swagger>js-yaml': 5.2.2
injectWorkspacePackages: true
allowBuilds:
  '@scarf/scarf': false
  esbuild: true
minimumReleaseAgeExclude:
  - '@nestjs/common@11.2.1'
  - '@nestjs/core@11.2.1'
  - '@nestjs/platform-fastify@11.2.1'
  - '@nestjs/testing@11.2.1'
  - '@tanstack/query-core@5.102.0'
  - '@tanstack/react-query@5.102.0'
